services:
  parser:
    build:
      context: .
      dockerfile: ./apps/parser/Dockerfile
      target: development
    command: npm run start:dev parser
    env_file:
      - ./apps/parser/.env
    depends_on:
      - mongodb
      - careers
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
  careers:
    build:
      context: .
      dockerfile: ./apps/careers/Dockerfile
      target: development
    command: npm run start:dev careers
    env_file:
      - ./apps/careers/.env
    depends_on:
      - mongodb
      - billing
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongodb
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  mongodb:
    image: 'mongo:latest'
    volumes:
      - mongodb_data:/data/db  
    ports:
      - '27017:27017'

volumes:
  mongodb_data: